import { useState } from 'react';
import type { ViewImage, ViewType } from '../types';
import { VIEW_OPTIONS } from '../types';

type Props = {
  viewImages: ViewImage[];
  onRegenerateAll: () => void;
  onRegenerateView: (view: ViewType) => void;
  onContinue: () => void;
  loading: boolean;
};

const viewLabel = (view: ViewType) =>
  VIEW_OPTIONS.find(v => v.key === view)?.label ?? view;

export function GeneratedImage({
  viewImages,
  onRegenerateAll,
  onRegenerateView,
  onContinue,
  loading,
}: Props) {
  const [activeView, setActiveView] = useState<ViewType>(viewImages[0]?.view ?? 'exterior');
  const activeImage = viewImages.find(vi => vi.view === activeView) ?? viewImages[0];

  const single = viewImages.length === 1;

  return (
    <section className="card">
      <h2>Design visual{single ? '' : 's'}</h2>
      <p className="muted">
        {single
          ? 'Generated by Flux from the plan. Regenerate for a different look, or continue to notes.'
          : `${viewImages.length} views generated. Click tabs to switch. Regenerate individual views or all at once.`}
      </p>

      {!single && (
        <div className="view-tabs">
          {viewImages.map(vi => (
            <button
              key={vi.view}
              className={'view-tab' + (vi.view === activeView ? ' active' : '')}
              onClick={() => setActiveView(vi.view)}
            >
              {viewLabel(vi.view)}
            </button>
          ))}
        </div>
      )}

      {activeImage && (
        <>
          <div className="image-frame">
            <img src={activeImage.url} alt={`${viewLabel(activeImage.view)} design visual`} />
          </div>

          <details className="prompt-details">
            <summary>Image prompt — {viewLabel(activeImage.view)}</summary>
            <pre>{activeImage.prompt}</pre>
          </details>
        </>
      )}

      <div className="actions">
        {!single && activeImage && (
          <button
            className="btn ghost"
            onClick={() => onRegenerateView(activeImage.view)}
            disabled={loading}
          >
            {loading ? 'Regenerating…' : `Regenerate ${viewLabel(activeImage.view).toLowerCase()}`}
          </button>
        )}
        <button className="btn ghost" onClick={onRegenerateAll} disabled={loading}>
          {loading ? 'Regenerating…' : single ? 'Regenerate image' : 'Regenerate all views'}
        </button>
        <button className="btn primary" onClick={onContinue} disabled={loading}>
          Add notes & save
        </button>
      </div>
    </section>
  );
}
